### DISCUSSION TITLE
Full toml config examples

### DISCUSSION THREAD

**Discussion by iacchus** [iacchus/birdears#35] [Birdears Discussion Forum]
We can do some full toml config examples.

**Comment by iacchus** [comment]
Here follows an example toml file. The file should be loaded via `birdears load`

### `example-melodicinterval-hard.toml`

```toml
exercise = 'melodic'

mode = 'major'

# tonic can be `str` or `list`
# tonic = 'C, D, G'
# tonic = ['C', 'D', 'G']
tonic = 'r' # random; all tonics

octave = 4
descending = true
chromatic = true
n_octaves = 2

# `str` or `list`
# valid_intervals = ['i', 'ii','iii','iv','iv','vi','vii']
valid_intervals = 'i, ii, iii, iv, v, vi, vii'

# in seconds; these are the times of
# prequestion, question and resolution:
# 1. playing time, 2. wait to play next element,
# and 3. delay after playing the last element
user_durations = """
1.2,      .5,      .75,
1.5,      1,       1,
1.2,        .5,     1"""

prequestion_method = 'progression_i_iv_v_i'
resolution_method = 'nearest_tonic'
```
